### ISSUE TITLE
/etc/nvidia/kernel.conf getting overwritten

### ISSUE THREAD

**Issue by brittyazel** [negativo17/nvidia-kmod-common#14]
Hello, thank you for all of your hard work maintaining up-to-date Nvidia drivers for myself and my department at the University of California, San Francisco.

We have a large number of Pascal GPUs that I manage for my department, and since the update to the 560 driver I have needed to modify `/etc/nvidia/kernel.conf` to use the "kernel" variant instead of the "kernel-open" variant. However, even after deploying this modified file out to our many systems, this file keeps getting replaced and moved to kernel.conf.rpmsave, leading to the "kernel-open" variant being repeatedly built instead.

The issue here seems to stem from `/etc/nvidia/kernel.conf` only being marked as `%config` rather than `%config(noreplace)`, as is explained [here](https://www.cl.cam.ac.uk/~jw35/docs/rpm_config.html). And, as this file is written _before_ the DKMS build happens, it means that I have to fix the file and manually re-build my DKMS modules each and every time we have a driver update.

Can you please mark this file as `%config(noreplace)` in the .spec so as to write the new file to .rpmnew instead of the other way around? I believe those of us with Volta/Pascal/Maxwell cards (and in my case dozens of them) would greatly appreciate not having to continually re-set this file. 

Thanks,

**Comment by brittyazel** [comment]
I believe #13 also touches on the above issue.

**Comment by scaronni** [comment]
Argh! Thanks for reporting. Will fix immediately. The moment I switched to using the open drivers by default, it's the same time I switched my GPUs to the new ones provided by Nvidia and never noticed it.

Fixed in https://github.com/negativo17/nvidia-kmod-common/commit/cfa44733fc24860a26d2e2e248e75bccc471f51a, online in a few minutes.

@brittyazel if you have any particular request / feedback please dm me. Thanks!

**Comment by brittyazel** [comment]
Thank you for getting a fix out so quickly! It's greatly appreciated.
